config/routes.rb
Rails.application.routes.draw do
  resources :albums
  resources :users

  root 'albums#index'
end

app/models/album.rb
class Album < ApplicationRecord
  include HTTParty

  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :albums
end

app/controllers/albums_controller.rb
require 'will_paginate/array'

class AlbumsController < ApplicationController
  def index
    @albums = HTTParty.get('https://jsonplaceholder.typicode.com/albums', :headers => {'Content-Type' => 'application/json'}).paginate(:page => params[:page], :per_page => 10)
    @albumPhotos = HTTParty.get('https://jsonplaceholder.typicode.com/photos?albums/', :headers => {'Content-Type' => 'application/json'})
    @users = HTTParty.get('https://jsonplaceholder.typicode.com/users', :headers => {'Content-Type' => 'application/json'})
  end

  def show
    @album = HTTParty.get('https://jsonplaceholder.typicode.com/albums/' + params[:id], :headers => {'Content-Type' => 'application/json'})
    @albumPhotos = HTTParty.get('https://jsonplaceholder.typicode.com/photos?album=' + params[:id], :headers => {'Content-Type' => 'application/json'}).paginate(:page => params[:page], :per_page => 10)
    @users = HTTParty.get('https://jsonplaceholder.typicode.com/users/', :headers => {'Content-Type' => 'application/json'})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = HTTParty.get('https://jsonplaceholder.typicode.com/users/' + params[:id], :headers => {'Content-Type' => 'application/json'})

    @albums = HTTParty
      .get('https://jsonplaceholder.typicode.com/albums', :headers => {'Content-Type' => 'application/json'})
      .select{|a| a['userId'] == @user['id']}
      .paginate(:page => params[:page], :per_page => 6)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<main role="main" class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Albums</h1>
    <p class="lead">Here we show all albums and it's details</p>

    <% cache do %>
    <div class="row">
      <% @albums.each do |album| %>
        <div class="col-md-4">
          <%= image_tag @albumPhotos.first{|ap| ap['id'] == album['id']}.try(:[], 'thumbnailUrl') || 'image not avaliable' %>
          <h5 class="card-title">
            <%= album['title'] %>
          </h5>

          <p>By: <%= link_to @users.find{|u| u['id'] == album['userId']}.try(:[], 'name') || 'not available', user_path(album['userId']) %><p>
          <%= link_to "View Album", album_path(album['id']), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>

  <%= will_paginate @albums, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, class: 'margin-auto' %>
</main>

app/views/albums/show.html.erb
<% cache do %>
<main role="main">
  <div class="container">
    <div class="row">
      <div class="col">
        <h2 class="mt-5">Album: <%= @album['title'] %></h2>
        <p class="lead">All of the photos in this album are below</p>

        <div class="row">
          <% @albumPhotos.each do |albumPhoto| %>
            <div class="col-md-4">
              <%= image_tag(albumPhoto['thumbnailUrl']) %>

              <h5 class="card-title">
                <%= albumPhoto['title'] %>
              </h5>
            </div>
          <% end %>
        </div>
      </div>

      <div class="col">
        <div class="card mt-5 mb-5">
          <div class="card-header">
            <h5>The creator of this album: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[], 'name') || 'not available' %></h5>
          </div>

            <div class="card-body">
              <h5 class="card-title">User details</h5>

              <ul class="card-text">
                <li>ID: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[], 'id') || 'not available' %></li>
                <li>Name: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[], 'name') || 'not available' %></li>
                <li>E-mail: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[], 'email') || 'not available' %></li>
              </ul>

              <ul>
                <h5>Address</h5>
                <li>Street: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[], 'address').try(:[],'street') || 'not available' %></li>
                <li>Suite: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[], 'address').try(:[],'suite') || 'not available' %></li>
                <li>City: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[], 'address').try(:[],'city') || 'not available' %></li>
                <li>Zipcode: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[], 'address').try(:[],'zipcode') || 'not available' %></li>
                <li>Geo Lat: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[], 'address').try(:[],'geo').try(:[], 'lat') || 'not available' %></li>
                <li>Geo Lng: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[], 'address').try(:[],'geo').try(:[], 'lng') || 'not available' %></li>
              </ul>

              <ul>
                <li>Phone Number: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[],'phone') || 'not available' %></li>
                <li>Website: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[],'website') || 'not available' %></li>
              </ul>

              <ul>
                <h5>Company details</h5>
                <li>Company name: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[], 'company').try(:[], 'name') || 'not available' %></li>
                <li>Company catchphrase: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[], 'company').try(:[], 'catchphrase') || 'not available' %></li>
                <li>Company bs: <%= @users.find{|u| u['id'] == @album['userId']}.try(:[], 'company').try(:[], 'name') || 'not available' %></li>
              </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= will_paginate @albumPhotos, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, class: 'margin-auto' %>
</main>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoGreen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/shared/navigation' %>
      <%= yield %>
  </body>
</html>

app/views/layouts/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Go Green", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "Albums", albums_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/users/show.html.erb
<% cache do %>
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <h5>Name: <%= @user['name'] %> | Username: <%= @user['username'] %></h5>
    </div>

    <div class="card-body">
      <h5 class="card-title">User details</h5>

      <ul class="card-text">
        <li>ID: <%= @user['id'] %></li>
        <li>Name: <%= @user['name'] %></li>
        <li>E-mail: <%= @user['email'] %></li>
      </ul>

      <ul>
        <h5>Address</h5>
        <li>Street: <%= @user['address']['street'] %></li>
        <li>Suite: <%= @user['address']['suite'] %></li>
        <li>City: <%= @user['address']['city'] %></li>
        <li>Zipcode: <%= @user['address']['zipcode'] %></li>
        <li>Geo Lat: <%= @user['address']['geo']['lat'] %></li>
        <li>Geo Lng: <%= @user['address']['geo']['lng'] %></li>
      </ul>

      <ul>
        <li>Phone Number: <%= @user['phone'] %></li>
        <li>Website: <%= @user['website'] %></li>
      </ul>

      <ul>
        <h5>Company details</h5>
        <li>Company name: <%= @user['company']['name'] %></li>
        <li>Company catchphrase: <%= @user['company']['catchPhrase'] %></li>
        <li>Company bs: <%= @user['company']['bs'] %></li>
      </ul>

      <h5 class="card-title">User Albums</h5>

      <div class="row">
        <% @albums.each do |album| %>
          <div class="col-md-4 mb-4">
            <h5 class="card-title">
              <%= album['title'] %>
            </h5>

            <%= link_to "View Album", album_path(album['id']), class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>

      <%= will_paginate @albums, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, class: 'margin-auto' %>
    </div>
  </div>
</div>
<% end %>